trap 'bye;' 2
bye () {
  echo "If you love me ,I will let you go"
  
}
echo -e "\e[1;31m__________________________________\e[0m" 
figlet 'MBAT'

password='MBAT'
Username='MBAT'
read -p "Username:" Name
read -sp "Password:" Password
if [[ $Name == $Username || $Password == $password ]];then
echo ""
echo -e "\e[1;31m__________________________________\e[0m" 
figlet 'Welcome'

else
echo ""
echo "\e[1;31m Myanmar young Script kiddies \e[0m" 
figlet 'wrong password KMKL' 
exit
fi

echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo -e "\e[1;35m Hey beautiful girl \e[0m"
echo -e "\e[1;31m Coder:b4ndu14\e[0m"
echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo -e "\e[1;31m__________________________________\e[0m" 
figlet 'MBAT'
echo -e "\e[1;31m ILOVEYOU  babe ,do you love me\e[0m "

echo -e "\e[1;31m 1.I Love You too \e[0m"
echo -e "\e[1;31m 2.I hate You \e[0m"
echo ""


read -p " Answer me 1 or 1~# " act
echo""

if [ $act = 1 ] || [ $act = 01 ];
then
clear

apt install toilet

clear
echo -e "\e[1;31m Love you too babe \e[0m"

toilet I love you

fi
for x in {1..10000};do
echo "$x I LOVE YOU 
I LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOUI LOVE YOU "
done 

if [ $act = 2 ] || [ $act = 02 ];
then
clear

figlet 'FUCK YOU'
fi
for x in {1..1000};do
echo "$x 
FUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOUFUCK YOU "
done
trap 2